import dbgui;
import sokol_debugtext;

import sokol_all;
import math;

// force high-dpi, sample entry point is __sapp_sample_main()
sapp_desc sokol_main() {
    sapp_desc d = __sapp_sample_main();
    d.high_dpi = true;
    return d;
}

// drawex-sapp.glsl - ported to minc @shader.

struct DrawexSappVsOut {
    float4 pos;
    float4 color;
}

@shader vertex
DrawexSappVsOut drawex_sapp_vs(
    @attr(0) float2 pos,
    @attr(1) float3 color0,
    @attr(2) float3 inst_data
) {
    DrawexSappVsOut o;
    float2 inst_pos = inst_data.xy;
    f32 inst_scale = inst_data.z;
    o.pos = float4{pos * inst_scale + inst_pos, 0, 1};
    o.color = float4{color0, 1};
    return o;
}

@shader fragment
float4 drawex_sapp_fs(
DrawexSappVsOut input
) {
    return input.color;
}


enum __enum_ATTR_drawex_pos {
    ATTR_drawex_pos = 0,
    ATTR_drawex_color0 = 1,
    ATTR_drawex_inst_data = 2,
    __shim_end = 255,
}

enum draw_mode_t {
    INVALID = 0,
    BASE_VERTEX_INSTANCE = 1,
    BASE_VERTEX = 2,
    BASE_INSTANCE = 4,
}

private struct state_t {
    sg_pass_action pass_action;
    sg_buffer vtx_buf;
    sg_buffer idx_buf;
    sg_buffer inst_buf;
    sg_pipeline pip;
    u8 supported_modes;
    draw_mode_t current_mode;
}

struct vertex_t {
    f32 x;
    f32 y;
    f32 r;
    f32 g;
    f32 b;
}

struct instance_t {
    f32 x;
    f32 y;
    f32 scale;
}

/*
    sokol_color.h -- sg_color utilities

    This header was generated by gen_sokol_color.py. Do not modify it.

    Project URL: https://github.com/floooh/sokol

    Include the following headers before including sokol_color.h:

        sokol_gfx.h

    FEATURE OVERVIEW
    ================
    sokol_color.h defines preset colors based on the X11 color names,
    alongside utility functions to create and modify sg_color objects.

    The predefined colors are based on the X11 color names:

        https://en.wikipedia.org/wiki/X11_color_names

    This palette is useful for prototyping - lots of programmers are familiar with
    these colours due to their use in X11, web development and XNA / MonoGame. They
    are also handy when you want to reference a familiar color, but don't want to
    write it out by hand.

    COLORS
    ======
    The palette is defined using static const (or constexpr if you are using a
    C++ compiler) objects. These objects use lowercase names:

        static SOKOL_COLOR_CONSTEXPR sg_color sg_red = SG_RED;
        static SOKOL_COLOR_CONSTEXPR sg_color sg_green = SG_GREEN;
        static SOKOL_COLOR_CONSTEXPR sg_color sg_blue = SG_BLUE;

    An sg_color preset object like sg_red can be used to initialize
    an sg_pass_action:

        sg_pass_action pass_action = {
            .colors[0] = { .action=SG_ACTION_CLEAR, .value = sg_red }
        };

    Initializing an object with static storage duration is more complicated
    because of C language rules. Technically, a static const is not a
    compile-time constant in C. To work around this, the palette is also
    defined as a series of brace-enclosed list macro definitions. These
    definitions use uppercase names:

        #define SG_RED { 1.0f, 0.0f, 0.0f, 1.0f }
        #define SG_GREEN { 0.0f, 1.0f, 0.0f, 1.0f }
        #define SG_BLUE { 0.0f, 0.0f, 1.0f, 1.0f }

    A preset macro like SG_RED can be used to initialize objects with static
    storage duration:

        static struct {
            sg_pass_action pass_action;
        } state = {
            .pass_action = {
                .colors[0] = { .action = SG_ACTION_CLEAR, .value = SG_RED }
            }
        };

    A second set of macro definitions exists for colors packed as 32 bit integer
    values. These definitions are also uppercase, but use the _RGBA32 suffix:

        #define SG_RED_RGBA32 0xFF0000FF
        #define SG_GREEN_RGBA32 0x00FF00FF
        #define SG_BLUE_RGBA32 0x0000FFFF

    This is useful if your code makes use of packed colors, as sokol_gl.h does for its
    internal vertex format:

        sgl_begin_triangles();
        sgl_v2f_c1i( 0.0f,  0.5f, SG_RED_RGBA32);
        sgl_v2f_c1i( 0.5f, -0.5f, SG_GREEN_RGBA32);
        sgl_v2f_c1i(-0.5f, -0.5f, SG_BLUE_RGBA32);
        sgl_end();

    UTILITY FUNCTIONS
    =================

    Utility functions for creating colours are provided:

        - sg_make_color_4b(uint8_t r, uint8_t g, uint8_t b, uint8_t a)
            Create a sg_color object from separate R, G, B, A bytes.

        - sg_make_color_1i(uint32_t rgba)
            Create a sg_color object from RGBA bytes packed into a 32-bit unsigned integer.

        - sg_color_lerp(const sg_color* color_a, const sg_color* color_b, float amount)
            Linearly interpolate a color.

        - sg_color_lerp_precise(const sg_color* color_a, const sg_color* color_b, float amount)
            Linearly interpolate a color. Less efficient but more precise than sg_color_lerp.

        - sg_color_multiply(const sg_color* color, float scale)
            Multiply each color component by the scale factor.

    LICENSE
    =======

    zlib/libpng license

    Copyright (c) 2020 Stuart Adams

    This software is provided 'as-is', without any express or implied warranty.
    In no event will the authors be held liable for any damages arising from the
    use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

        1. The origin of this software must not be misrepresented; you must not
        claim that you wrote the original software. If you use this software in a
        product, an acknowledgment in the product documentation would be
        appreciated but is not required.

        2. Altered source versions must be plainly marked as such, and must not
        be misrepresented as being the original software.

        3. This notice may not be removed or altered from any source
        distribution.
*/
/* Alice Blue color { R:240, G:248, B:255, A:255 } */
/* Antique White color { R:250, G:235, B:215, A:255 } */
/* Aqua color { R:0, G:255, B:255, A:255 } */
/* Aquamarine color { R:127, G:255, B:212, A:255 } */
/* Azure color { R:240, G:255, B:255, A:255 } */
/* Beige color { R:245, G:245, B:220, A:255 } */
/* Bisque color { R:255, G:228, B:196, A:255 } */
/* Black color { R:0, G:0, B:0, A:255 } */
/* Blanched Almond color { R:255, G:235, B:205, A:255 } */
/* Blue color { R:0, G:0, B:255, A:255 } */
/* Blue Violet color { R:138, G:43, B:226, A:255 } */
/* Brown color { R:165, G:42, B:42, A:255 } */
/* Burlywood color { R:222, G:184, B:135, A:255 } */
/* Cadet Blue color { R:95, G:158, B:160, A:255 } */
/* Chartreuse color { R:127, G:255, B:0, A:255 } */
/* Chocolate color { R:210, G:105, B:30, A:255 } */
/* Coral color { R:255, G:127, B:80, A:255 } */
/* Cornflower Blue color { R:100, G:149, B:237, A:255 } */
/* Cornsilk color { R:255, G:248, B:220, A:255 } */
/* Crimson color { R:220, G:20, B:60, A:255 } */
/* Cyan color { R:0, G:255, B:255, A:255 } */
/* Dark Blue color { R:0, G:0, B:139, A:255 } */
/* Dark Cyan color { R:0, G:139, B:139, A:255 } */
/* Dark Goldenrod color { R:184, G:134, B:11, A:255 } */
/* Dark Gray color { R:169, G:169, B:169, A:255 } */
/* Dark Green color { R:0, G:100, B:0, A:255 } */
/* Dark Khaki color { R:189, G:183, B:107, A:255 } */
/* Dark Magenta color { R:139, G:0, B:139, A:255 } */
/* Dark Olive Green color { R:85, G:107, B:47, A:255 } */
/* Dark Orange color { R:255, G:140, B:0, A:255 } */
/* Dark Orchid color { R:153, G:50, B:204, A:255 } */
/* Dark Red color { R:139, G:0, B:0, A:255 } */
/* Dark Salmon color { R:233, G:150, B:122, A:255 } */
/* Dark Sea Green color { R:143, G:188, B:143, A:255 } */
/* Dark Slate Blue color { R:72, G:61, B:139, A:255 } */
/* Dark Slate Gray color { R:47, G:79, B:79, A:255 } */
/* Dark Turquoise color { R:0, G:206, B:209, A:255 } */
/* Dark Violet color { R:148, G:0, B:211, A:255 } */
/* Deep Pink color { R:255, G:20, B:147, A:255 } */
/* Deep Sky Blue color { R:0, G:191, B:255, A:255 } */
/* Dim Gray color { R:105, G:105, B:105, A:255 } */
/* Dodger Blue color { R:30, G:144, B:255, A:255 } */
/* Firebrick color { R:178, G:34, B:34, A:255 } */
/* Floral White color { R:255, G:250, B:240, A:255 } */
/* Forest Green color { R:34, G:139, B:34, A:255 } */
/* Fuchsia color { R:255, G:0, B:255, A:255 } */
/* Gainsboro color { R:220, G:220, B:220, A:255 } */
/* Ghost White color { R:248, G:248, B:255, A:255 } */
/* Gold color { R:255, G:215, B:0, A:255 } */
/* Goldenrod color { R:218, G:165, B:32, A:255 } */
/* Gray color { R:190, G:190, B:190, A:255 } */
/* Web Gray color { R:128, G:128, B:128, A:255 } */
/* Green color { R:0, G:255, B:0, A:255 } */
/* Web Green color { R:0, G:128, B:0, A:255 } */
/* Green Yellow color { R:173, G:255, B:47, A:255 } */
/* Honeydew color { R:240, G:255, B:240, A:255 } */
/* Hot Pink color { R:255, G:105, B:180, A:255 } */
/* Indian Red color { R:205, G:92, B:92, A:255 } */
/* Indigo color { R:75, G:0, B:130, A:255 } */
/* Ivory color { R:255, G:255, B:240, A:255 } */
/* Khaki color { R:240, G:230, B:140, A:255 } */
/* Lavender color { R:230, G:230, B:250, A:255 } */
/* Lavender Blush color { R:255, G:240, B:245, A:255 } */
/* Lawn Green color { R:124, G:252, B:0, A:255 } */
/* Lemon Chiffon color { R:255, G:250, B:205, A:255 } */
/* Light Blue color { R:173, G:216, B:230, A:255 } */
/* Light Coral color { R:240, G:128, B:128, A:255 } */
/* Light Cyan color { R:224, G:255, B:255, A:255 } */
/* Light Goldenrod color { R:250, G:250, B:210, A:255 } */
/* Light Gray color { R:211, G:211, B:211, A:255 } */
/* Light Green color { R:144, G:238, B:144, A:255 } */
/* Light Pink color { R:255, G:182, B:193, A:255 } */
/* Light Salmon color { R:255, G:160, B:122, A:255 } */
/* Light Sea Green color { R:32, G:178, B:170, A:255 } */
/* Light Sky Blue color { R:135, G:206, B:250, A:255 } */
/* Light Slate Gray color { R:119, G:136, B:153, A:255 } */
/* Light Steel Blue color { R:176, G:196, B:222, A:255 } */
/* Light Yellow color { R:255, G:255, B:224, A:255 } */
/* Lime color { R:0, G:255, B:0, A:255 } */
/* Lime Green color { R:50, G:205, B:50, A:255 } */
/* Linen color { R:250, G:240, B:230, A:255 } */
/* Magenta color { R:255, G:0, B:255, A:255 } */
/* Maroon color { R:176, G:48, B:96, A:255 } */
/* Web Maroon color { R:128, G:0, B:0, A:255 } */
/* Medium Aquamarine color { R:102, G:205, B:170, A:255 } */
/* Medium Blue color { R:0, G:0, B:205, A:255 } */
/* Medium Orchid color { R:186, G:85, B:211, A:255 } */
/* Medium Purple color { R:147, G:112, B:219, A:255 } */
/* Medium Sea Green color { R:60, G:179, B:113, A:255 } */
/* Medium Slate Blue color { R:123, G:104, B:238, A:255 } */
/* Medium Spring Green color { R:0, G:250, B:154, A:255 } */
/* Medium Turquoise color { R:72, G:209, B:204, A:255 } */
/* Medium Violet Red color { R:199, G:21, B:133, A:255 } */
/* Midnight Blue color { R:25, G:25, B:112, A:255 } */
/* Mint Cream color { R:245, G:255, B:250, A:255 } */
/* Misty Rose color { R:255, G:228, B:225, A:255 } */
/* Moccasin color { R:255, G:228, B:181, A:255 } */
/* Navajo White color { R:255, G:222, B:173, A:255 } */
/* Navy Blue color { R:0, G:0, B:128, A:255 } */
/* Old Lace color { R:253, G:245, B:230, A:255 } */
/* Olive color { R:128, G:128, B:0, A:255 } */
/* Olive Drab color { R:107, G:142, B:35, A:255 } */
/* Orange color { R:255, G:165, B:0, A:255 } */
/* Orange Red color { R:255, G:69, B:0, A:255 } */
/* Orchid color { R:218, G:112, B:214, A:255 } */
/* Pale Goldenrod color { R:238, G:232, B:170, A:255 } */
/* Pale Green color { R:152, G:251, B:152, A:255 } */
/* Pale Turquoise color { R:175, G:238, B:238, A:255 } */
/* Pale Violet Red color { R:219, G:112, B:147, A:255 } */
/* Papaya Whip color { R:255, G:239, B:213, A:255 } */
/* Peach Puff color { R:255, G:218, B:185, A:255 } */
/* Peru color { R:205, G:133, B:63, A:255 } */
/* Pink color { R:255, G:192, B:203, A:255 } */
/* Plum color { R:221, G:160, B:221, A:255 } */
/* Powder Blue color { R:176, G:224, B:230, A:255 } */
/* Purple color { R:160, G:32, B:240, A:255 } */
/* Web Purple color { R:128, G:0, B:128, A:255 } */
/* Rebecca Purple color { R:102, G:51, B:153, A:255 } */
/* Red color { R:255, G:0, B:0, A:255 } */
/* Rosy Brown color { R:188, G:143, B:143, A:255 } */
/* Royal Blue color { R:65, G:105, B:225, A:255 } */
/* Saddle Brown color { R:139, G:69, B:19, A:255 } */
/* Salmon color { R:250, G:128, B:114, A:255 } */
/* Sandy Brown color { R:244, G:164, B:96, A:255 } */
/* Sea Green color { R:46, G:139, B:87, A:255 } */
/* Seashell color { R:255, G:245, B:238, A:255 } */
/* Sienna color { R:160, G:82, B:45, A:255 } */
/* Silver color { R:192, G:192, B:192, A:255 } */
/* Sky Blue color { R:135, G:206, B:235, A:255 } */
/* Slate Blue color { R:106, G:90, B:205, A:255 } */
/* Slate Gray color { R:112, G:128, B:144, A:255 } */
/* Snow color { R:255, G:250, B:250, A:255 } */
/* Spring Green color { R:0, G:255, B:127, A:255 } */
/* Steel Blue color { R:70, G:130, B:180, A:255 } */
/* Tan color { R:210, G:180, B:140, A:255 } */
/* Teal color { R:0, G:128, B:128, A:255 } */
/* Thistle color { R:216, G:191, B:216, A:255 } */
/* Tomato color { R:255, G:99, B:71, A:255 } */
/* Transparent color { R:0, G:0, B:0, A:0 } */
/* Turquoise color { R:64, G:224, B:208, A:255 } */
/* Violet color { R:238, G:130, B:238, A:255 } */
/* Wheat color { R:245, G:222, B:179, A:255 } */
/* White color { R:255, G:255, B:255, A:255 } */
/* White Smoke color { R:245, G:245, B:245, A:255 } */
/* Yellow color { R:255, G:255, B:0, A:255 } */
/* Yellow Green color { R:154, G:205, B:50, A:255 } */
/* Alice Blue color { R:240, G:248, B:255, A:255 } */
private {
sg_color sg_alice_blue = sg_color{0.941176471f, 0.97254902f, 1.0f, 1.0f};
/* Antique White color { R:250, G:235, B:215, A:255 } */
sg_color sg_antique_white = sg_color{0.980392157f, 0.921568627f, 0.843137255f, 1.0f};
/* Aqua color { R:0, G:255, B:255, A:255 } */
sg_color sg_aqua = sg_color{0.0f, 1.0f, 1.0f, 1.0f};
/* Aquamarine color { R:127, G:255, B:212, A:255 } */
sg_color sg_aquamarine = sg_color{0.498039216f, 1.0f, 0.831372549f, 1.0f};
/* Azure color { R:240, G:255, B:255, A:255 } */
sg_color sg_azure = sg_color{0.941176471f, 1.0f, 1.0f, 1.0f};
/* Beige color { R:245, G:245, B:220, A:255 } */
sg_color sg_beige = sg_color{0.960784314f, 0.960784314f, 0.862745098f, 1.0f};
/* Bisque color { R:255, G:228, B:196, A:255 } */
sg_color sg_bisque = sg_color{1.0f, 0.894117647f, 0.768627451f, 1.0f};
/* Black color { R:0, G:0, B:0, A:255 } */
sg_color sg_black = sg_color{0.0f, 0.0f, 0.0f, 1.0f};
/* Blanched Almond color { R:255, G:235, B:205, A:255 } */
sg_color sg_blanched_almond = sg_color{1.0f, 0.921568627f, 0.803921569f, 1.0f};
/* Blue color { R:0, G:0, B:255, A:255 } */
sg_color sg_blue = sg_color{0.0f, 0.0f, 1.0f, 1.0f};
/* Blue Violet color { R:138, G:43, B:226, A:255 } */
sg_color sg_blue_violet = sg_color{0.541176471f, 0.168627451f, 0.88627451f, 1.0f};
/* Brown color { R:165, G:42, B:42, A:255 } */
sg_color sg_brown = sg_color{0.647058824f, 0.164705882f, 0.164705882f, 1.0f};
/* Burlywood color { R:222, G:184, B:135, A:255 } */
sg_color sg_burlywood = sg_color{0.870588235f, 0.721568627f, 0.529411765f, 1.0f};
/* Cadet Blue color { R:95, G:158, B:160, A:255 } */
sg_color sg_cadet_blue = sg_color{0.37254902f, 0.619607843f, 0.62745098f, 1.0f};
/* Chartreuse color { R:127, G:255, B:0, A:255 } */
sg_color sg_chartreuse = sg_color{0.498039216f, 1.0f, 0.0f, 1.0f};
/* Chocolate color { R:210, G:105, B:30, A:255 } */
sg_color sg_chocolate = sg_color{0.823529412f, 0.411764706f, 0.117647059f, 1.0f};
/* Coral color { R:255, G:127, B:80, A:255 } */
sg_color sg_coral = sg_color{1.0f, 0.498039216f, 0.31372549f, 1.0f};
/* Cornflower Blue color { R:100, G:149, B:237, A:255 } */
sg_color sg_cornflower_blue = sg_color{0.392156863f, 0.584313725f, 0.929411765f, 1.0f};
/* Cornsilk color { R:255, G:248, B:220, A:255 } */
sg_color sg_cornsilk = sg_color{1.0f, 0.97254902f, 0.862745098f, 1.0f};
/* Crimson color { R:220, G:20, B:60, A:255 } */
sg_color sg_crimson = sg_color{0.862745098f, 0.0784313725f, 0.235294118f, 1.0f};
/* Cyan color { R:0, G:255, B:255, A:255 } */
sg_color sg_cyan = sg_color{0.0f, 1.0f, 1.0f, 1.0f};
/* Dark Blue color { R:0, G:0, B:139, A:255 } */
sg_color sg_dark_blue = sg_color{0.0f, 0.0f, 0.545098039f, 1.0f};
/* Dark Cyan color { R:0, G:139, B:139, A:255 } */
sg_color sg_dark_cyan = sg_color{0.0f, 0.545098039f, 0.545098039f, 1.0f};
/* Dark Goldenrod color { R:184, G:134, B:11, A:255 } */
sg_color sg_dark_goldenrod = sg_color{0.721568627f, 0.525490196f, 0.0431372549f, 1.0f};
/* Dark Gray color { R:169, G:169, B:169, A:255 } */
sg_color sg_dark_gray = sg_color{0.662745098f, 0.662745098f, 0.662745098f, 1.0f};
/* Dark Green color { R:0, G:100, B:0, A:255 } */
sg_color sg_dark_green = sg_color{0.0f, 0.392156863f, 0.0f, 1.0f};
/* Dark Khaki color { R:189, G:183, B:107, A:255 } */
sg_color sg_dark_khaki = sg_color{0.741176471f, 0.717647059f, 0.419607843f, 1.0f};
/* Dark Magenta color { R:139, G:0, B:139, A:255 } */
sg_color sg_dark_magenta = sg_color{0.545098039f, 0.0f, 0.545098039f, 1.0f};
/* Dark Olive Green color { R:85, G:107, B:47, A:255 } */
sg_color sg_dark_olive_green = sg_color{0.333333333f, 0.419607843f, 0.184313725f, 1.0f};
/* Dark Orange color { R:255, G:140, B:0, A:255 } */
sg_color sg_dark_orange = sg_color{1.0f, 0.549019608f, 0.0f, 1.0f};
/* Dark Orchid color { R:153, G:50, B:204, A:255 } */
sg_color sg_dark_orchid = sg_color{0.6f, 0.196078431f, 0.8f, 1.0f};
/* Dark Red color { R:139, G:0, B:0, A:255 } */
sg_color sg_dark_red = sg_color{0.545098039f, 0.0f, 0.0f, 1.0f};
/* Dark Salmon color { R:233, G:150, B:122, A:255 } */
sg_color sg_dark_salmon = sg_color{0.91372549f, 0.588235294f, 0.478431373f, 1.0f};
/* Dark Sea Green color { R:143, G:188, B:143, A:255 } */
sg_color sg_dark_sea_green = sg_color{0.560784314f, 0.737254902f, 0.560784314f, 1.0f};
/* Dark Slate Blue color { R:72, G:61, B:139, A:255 } */
sg_color sg_dark_slate_blue = sg_color{0.282352941f, 0.239215686f, 0.545098039f, 1.0f};
/* Dark Slate Gray color { R:47, G:79, B:79, A:255 } */
sg_color sg_dark_slate_gray = sg_color{0.184313725f, 0.309803922f, 0.309803922f, 1.0f};
/* Dark Turquoise color { R:0, G:206, B:209, A:255 } */
sg_color sg_dark_turquoise = sg_color{0.0f, 0.807843137f, 0.819607843f, 1.0f};
/* Dark Violet color { R:148, G:0, B:211, A:255 } */
sg_color sg_dark_violet = sg_color{0.580392157f, 0.0f, 0.82745098f, 1.0f};
/* Deep Pink color { R:255, G:20, B:147, A:255 } */
sg_color sg_deep_pink = sg_color{1.0f, 0.0784313725f, 0.576470588f, 1.0f};
/* Deep Sky Blue color { R:0, G:191, B:255, A:255 } */
sg_color sg_deep_sky_blue = sg_color{0.0f, 0.749019608f, 1.0f, 1.0f};
/* Dim Gray color { R:105, G:105, B:105, A:255 } */
sg_color sg_dim_gray = sg_color{0.411764706f, 0.411764706f, 0.411764706f, 1.0f};
/* Dodger Blue color { R:30, G:144, B:255, A:255 } */
sg_color sg_dodger_blue = sg_color{0.117647059f, 0.564705882f, 1.0f, 1.0f};
/* Firebrick color { R:178, G:34, B:34, A:255 } */
sg_color sg_firebrick = sg_color{0.698039216f, 0.133333333f, 0.133333333f, 1.0f};
/* Floral White color { R:255, G:250, B:240, A:255 } */
sg_color sg_floral_white = sg_color{1.0f, 0.980392157f, 0.941176471f, 1.0f};
/* Forest Green color { R:34, G:139, B:34, A:255 } */
sg_color sg_forest_green = sg_color{0.133333333f, 0.545098039f, 0.133333333f, 1.0f};
/* Fuchsia color { R:255, G:0, B:255, A:255 } */
sg_color sg_fuchsia = sg_color{1.0f, 0.0f, 1.0f, 1.0f};
/* Gainsboro color { R:220, G:220, B:220, A:255 } */
sg_color sg_gainsboro = sg_color{0.862745098f, 0.862745098f, 0.862745098f, 1.0f};
/* Ghost White color { R:248, G:248, B:255, A:255 } */
sg_color sg_ghost_white = sg_color{0.97254902f, 0.97254902f, 1.0f, 1.0f};
/* Gold color { R:255, G:215, B:0, A:255 } */
sg_color sg_gold = sg_color{1.0f, 0.843137255f, 0.0f, 1.0f};
/* Goldenrod color { R:218, G:165, B:32, A:255 } */
sg_color sg_goldenrod = sg_color{0.854901961f, 0.647058824f, 0.125490196f, 1.0f};
/* Gray color { R:190, G:190, B:190, A:255 } */
sg_color sg_gray = sg_color{0.745098039f, 0.745098039f, 0.745098039f, 1.0f};
/* Web Gray color { R:128, G:128, B:128, A:255 } */
sg_color sg_web_gray = sg_color{0.501960784f, 0.501960784f, 0.501960784f, 1.0f};
/* Green color { R:0, G:255, B:0, A:255 } */
sg_color sg_green = sg_color{0.0f, 1.0f, 0.0f, 1.0f};
/* Web Green color { R:0, G:128, B:0, A:255 } */
sg_color sg_web_green = sg_color{0.0f, 0.501960784f, 0.0f, 1.0f};
/* Green Yellow color { R:173, G:255, B:47, A:255 } */
sg_color sg_green_yellow = sg_color{0.678431373f, 1.0f, 0.184313725f, 1.0f};
/* Honeydew color { R:240, G:255, B:240, A:255 } */
sg_color sg_honeydew = sg_color{0.941176471f, 1.0f, 0.941176471f, 1.0f};
/* Hot Pink color { R:255, G:105, B:180, A:255 } */
sg_color sg_hot_pink = sg_color{1.0f, 0.411764706f, 0.705882353f, 1.0f};
/* Indian Red color { R:205, G:92, B:92, A:255 } */
sg_color sg_indian_red = sg_color{0.803921569f, 0.360784314f, 0.360784314f, 1.0f};
/* Indigo color { R:75, G:0, B:130, A:255 } */
sg_color sg_indigo = sg_color{0.294117647f, 0.0f, 0.509803922f, 1.0f};
/* Ivory color { R:255, G:255, B:240, A:255 } */
sg_color sg_ivory = sg_color{1.0f, 1.0f, 0.941176471f, 1.0f};
/* Khaki color { R:240, G:230, B:140, A:255 } */
sg_color sg_khaki = sg_color{0.941176471f, 0.901960784f, 0.549019608f, 1.0f};
/* Lavender color { R:230, G:230, B:250, A:255 } */
sg_color sg_lavender = sg_color{0.901960784f, 0.901960784f, 0.980392157f, 1.0f};
/* Lavender Blush color { R:255, G:240, B:245, A:255 } */
sg_color sg_lavender_blush = sg_color{1.0f, 0.941176471f, 0.960784314f, 1.0f};
/* Lawn Green color { R:124, G:252, B:0, A:255 } */
sg_color sg_lawn_green = sg_color{0.48627451f, 0.988235294f, 0.0f, 1.0f};
/* Lemon Chiffon color { R:255, G:250, B:205, A:255 } */
sg_color sg_lemon_chiffon = sg_color{1.0f, 0.980392157f, 0.803921569f, 1.0f};
/* Light Blue color { R:173, G:216, B:230, A:255 } */
sg_color sg_light_blue = sg_color{0.678431373f, 0.847058824f, 0.901960784f, 1.0f};
/* Light Coral color { R:240, G:128, B:128, A:255 } */
sg_color sg_light_coral = sg_color{0.941176471f, 0.501960784f, 0.501960784f, 1.0f};
/* Light Cyan color { R:224, G:255, B:255, A:255 } */
sg_color sg_light_cyan = sg_color{0.878431373f, 1.0f, 1.0f, 1.0f};
/* Light Goldenrod color { R:250, G:250, B:210, A:255 } */
sg_color sg_light_goldenrod = sg_color{0.980392157f, 0.980392157f, 0.823529412f, 1.0f};
/* Light Gray color { R:211, G:211, B:211, A:255 } */
sg_color sg_light_gray = sg_color{0.82745098f, 0.82745098f, 0.82745098f, 1.0f};
/* Light Green color { R:144, G:238, B:144, A:255 } */
sg_color sg_light_green = sg_color{0.564705882f, 0.933333333f, 0.564705882f, 1.0f};
/* Light Pink color { R:255, G:182, B:193, A:255 } */
sg_color sg_light_pink = sg_color{1.0f, 0.71372549f, 0.756862745f, 1.0f};
/* Light Salmon color { R:255, G:160, B:122, A:255 } */
sg_color sg_light_salmon = sg_color{1.0f, 0.62745098f, 0.478431373f, 1.0f};
/* Light Sea Green color { R:32, G:178, B:170, A:255 } */
sg_color sg_light_sea_green = sg_color{0.125490196f, 0.698039216f, 0.666666667f, 1.0f};
/* Light Sky Blue color { R:135, G:206, B:250, A:255 } */
sg_color sg_light_sky_blue = sg_color{0.529411765f, 0.807843137f, 0.980392157f, 1.0f};
/* Light Slate Gray color { R:119, G:136, B:153, A:255 } */
sg_color sg_light_slate_gray = sg_color{0.466666667f, 0.533333333f, 0.6f, 1.0f};
/* Light Steel Blue color { R:176, G:196, B:222, A:255 } */
sg_color sg_light_steel_blue = sg_color{0.690196078f, 0.768627451f, 0.870588235f, 1.0f};
/* Light Yellow color { R:255, G:255, B:224, A:255 } */
sg_color sg_light_yellow = sg_color{1.0f, 1.0f, 0.878431373f, 1.0f};
/* Lime color { R:0, G:255, B:0, A:255 } */
sg_color sg_lime = sg_color{0.0f, 1.0f, 0.0f, 1.0f};
/* Lime Green color { R:50, G:205, B:50, A:255 } */
sg_color sg_lime_green = sg_color{0.196078431f, 0.803921569f, 0.196078431f, 1.0f};
/* Linen color { R:250, G:240, B:230, A:255 } */
sg_color sg_linen = sg_color{0.980392157f, 0.941176471f, 0.901960784f, 1.0f};
/* Magenta color { R:255, G:0, B:255, A:255 } */
sg_color sg_magenta = sg_color{1.0f, 0.0f, 1.0f, 1.0f};
/* Maroon color { R:176, G:48, B:96, A:255 } */
sg_color sg_maroon = sg_color{0.690196078f, 0.188235294f, 0.376470588f, 1.0f};
/* Web Maroon color { R:128, G:0, B:0, A:255 } */
sg_color sg_web_maroon = sg_color{0.501960784f, 0.0f, 0.0f, 1.0f};
/* Medium Aquamarine color { R:102, G:205, B:170, A:255 } */
sg_color sg_medium_aquamarine = sg_color{0.4f, 0.803921569f, 0.666666667f, 1.0f};
/* Medium Blue color { R:0, G:0, B:205, A:255 } */
sg_color sg_medium_blue = sg_color{0.0f, 0.0f, 0.803921569f, 1.0f};
/* Medium Orchid color { R:186, G:85, B:211, A:255 } */
sg_color sg_medium_orchid = sg_color{0.729411765f, 0.333333333f, 0.82745098f, 1.0f};
/* Medium Purple color { R:147, G:112, B:219, A:255 } */
sg_color sg_medium_purple = sg_color{0.576470588f, 0.439215686f, 0.858823529f, 1.0f};
/* Medium Sea Green color { R:60, G:179, B:113, A:255 } */
sg_color sg_medium_sea_green = sg_color{0.235294118f, 0.701960784f, 0.443137255f, 1.0f};
/* Medium Slate Blue color { R:123, G:104, B:238, A:255 } */
sg_color sg_medium_slate_blue = sg_color{0.482352941f, 0.407843137f, 0.933333333f, 1.0f};
/* Medium Spring Green color { R:0, G:250, B:154, A:255 } */
sg_color sg_medium_spring_green = sg_color{0.0f, 0.980392157f, 0.603921569f, 1.0f};
/* Medium Turquoise color { R:72, G:209, B:204, A:255 } */
sg_color sg_medium_turquoise = sg_color{0.282352941f, 0.819607843f, 0.8f, 1.0f};
/* Medium Violet Red color { R:199, G:21, B:133, A:255 } */
sg_color sg_medium_violet_red = sg_color{0.780392157f, 0.0823529412f, 0.521568627f, 1.0f};
/* Midnight Blue color { R:25, G:25, B:112, A:255 } */
sg_color sg_midnight_blue = sg_color{0.0980392157f, 0.0980392157f, 0.439215686f, 1.0f};
/* Mint Cream color { R:245, G:255, B:250, A:255 } */
sg_color sg_mint_cream = sg_color{0.960784314f, 1.0f, 0.980392157f, 1.0f};
/* Misty Rose color { R:255, G:228, B:225, A:255 } */
sg_color sg_misty_rose = sg_color{1.0f, 0.894117647f, 0.882352941f, 1.0f};
/* Moccasin color { R:255, G:228, B:181, A:255 } */
sg_color sg_moccasin = sg_color{1.0f, 0.894117647f, 0.709803922f, 1.0f};
/* Navajo White color { R:255, G:222, B:173, A:255 } */
sg_color sg_navajo_white = sg_color{1.0f, 0.870588235f, 0.678431373f, 1.0f};
/* Navy Blue color { R:0, G:0, B:128, A:255 } */
sg_color sg_navy_blue = sg_color{0.0f, 0.0f, 0.501960784f, 1.0f};
/* Old Lace color { R:253, G:245, B:230, A:255 } */
sg_color sg_old_lace = sg_color{0.992156863f, 0.960784314f, 0.901960784f, 1.0f};
/* Olive color { R:128, G:128, B:0, A:255 } */
sg_color sg_olive = sg_color{0.501960784f, 0.501960784f, 0.0f, 1.0f};
/* Olive Drab color { R:107, G:142, B:35, A:255 } */
sg_color sg_olive_drab = sg_color{0.419607843f, 0.556862745f, 0.137254902f, 1.0f};
/* Orange color { R:255, G:165, B:0, A:255 } */
sg_color sg_orange = sg_color{1.0f, 0.647058824f, 0.0f, 1.0f};
/* Orange Red color { R:255, G:69, B:0, A:255 } */
sg_color sg_orange_red = sg_color{1.0f, 0.270588235f, 0.0f, 1.0f};
/* Orchid color { R:218, G:112, B:214, A:255 } */
sg_color sg_orchid = sg_color{0.854901961f, 0.439215686f, 0.839215686f, 1.0f};
/* Pale Goldenrod color { R:238, G:232, B:170, A:255 } */
sg_color sg_pale_goldenrod = sg_color{0.933333333f, 0.909803922f, 0.666666667f, 1.0f};
/* Pale Green color { R:152, G:251, B:152, A:255 } */
sg_color sg_pale_green = sg_color{0.596078431f, 0.984313725f, 0.596078431f, 1.0f};
/* Pale Turquoise color { R:175, G:238, B:238, A:255 } */
sg_color sg_pale_turquoise = sg_color{0.68627451f, 0.933333333f, 0.933333333f, 1.0f};
/* Pale Violet Red color { R:219, G:112, B:147, A:255 } */
sg_color sg_pale_violet_red = sg_color{0.858823529f, 0.439215686f, 0.576470588f, 1.0f};
/* Papaya Whip color { R:255, G:239, B:213, A:255 } */
sg_color sg_papaya_whip = sg_color{1.0f, 0.937254902f, 0.835294118f, 1.0f};
/* Peach Puff color { R:255, G:218, B:185, A:255 } */
sg_color sg_peach_puff = sg_color{1.0f, 0.854901961f, 0.725490196f, 1.0f};
/* Peru color { R:205, G:133, B:63, A:255 } */
sg_color sg_peru = sg_color{0.803921569f, 0.521568627f, 0.247058824f, 1.0f};
/* Pink color { R:255, G:192, B:203, A:255 } */
sg_color sg_pink = sg_color{1.0f, 0.752941176f, 0.796078431f, 1.0f};
/* Plum color { R:221, G:160, B:221, A:255 } */
sg_color sg_plum = sg_color{0.866666667f, 0.62745098f, 0.866666667f, 1.0f};
/* Powder Blue color { R:176, G:224, B:230, A:255 } */
sg_color sg_powder_blue = sg_color{0.690196078f, 0.878431373f, 0.901960784f, 1.0f};
/* Purple color { R:160, G:32, B:240, A:255 } */
sg_color sg_purple = sg_color{0.62745098f, 0.125490196f, 0.941176471f, 1.0f};
/* Web Purple color { R:128, G:0, B:128, A:255 } */
sg_color sg_web_purple = sg_color{0.501960784f, 0.0f, 0.501960784f, 1.0f};
/* Rebecca Purple color { R:102, G:51, B:153, A:255 } */
sg_color sg_rebecca_purple = sg_color{0.4f, 0.2f, 0.6f, 1.0f};
/* Red color { R:255, G:0, B:0, A:255 } */
sg_color sg_red = sg_color{1.0f, 0.0f, 0.0f, 1.0f};
/* Rosy Brown color { R:188, G:143, B:143, A:255 } */
sg_color sg_rosy_brown = sg_color{0.737254902f, 0.560784314f, 0.560784314f, 1.0f};
/* Royal Blue color { R:65, G:105, B:225, A:255 } */
sg_color sg_royal_blue = sg_color{0.254901961f, 0.411764706f, 0.882352941f, 1.0f};
/* Saddle Brown color { R:139, G:69, B:19, A:255 } */
sg_color sg_saddle_brown = sg_color{0.545098039f, 0.270588235f, 0.0745098039f, 1.0f};
/* Salmon color { R:250, G:128, B:114, A:255 } */
sg_color sg_salmon = sg_color{0.980392157f, 0.501960784f, 0.447058824f, 1.0f};
/* Sandy Brown color { R:244, G:164, B:96, A:255 } */
sg_color sg_sandy_brown = sg_color{0.956862745f, 0.643137255f, 0.376470588f, 1.0f};
/* Sea Green color { R:46, G:139, B:87, A:255 } */
sg_color sg_sea_green = sg_color{0.180392157f, 0.545098039f, 0.341176471f, 1.0f};
/* Seashell color { R:255, G:245, B:238, A:255 } */
sg_color sg_seashell = sg_color{1.0f, 0.960784314f, 0.933333333f, 1.0f};
/* Sienna color { R:160, G:82, B:45, A:255 } */
sg_color sg_sienna = sg_color{0.62745098f, 0.321568627f, 0.176470588f, 1.0f};
/* Silver color { R:192, G:192, B:192, A:255 } */
sg_color sg_silver = sg_color{0.752941176f, 0.752941176f, 0.752941176f, 1.0f};
/* Sky Blue color { R:135, G:206, B:235, A:255 } */
sg_color sg_sky_blue = sg_color{0.529411765f, 0.807843137f, 0.921568627f, 1.0f};
/* Slate Blue color { R:106, G:90, B:205, A:255 } */
sg_color sg_slate_blue = sg_color{0.415686275f, 0.352941176f, 0.803921569f, 1.0f};
/* Slate Gray color { R:112, G:128, B:144, A:255 } */
sg_color sg_slate_gray = sg_color{0.439215686f, 0.501960784f, 0.564705882f, 1.0f};
/* Snow color { R:255, G:250, B:250, A:255 } */
sg_color sg_snow = sg_color{1.0f, 0.980392157f, 0.980392157f, 1.0f};
/* Spring Green color { R:0, G:255, B:127, A:255 } */
sg_color sg_spring_green = sg_color{0.0f, 1.0f, 0.498039216f, 1.0f};
/* Steel Blue color { R:70, G:130, B:180, A:255 } */
sg_color sg_steel_blue = sg_color{0.274509804f, 0.509803922f, 0.705882353f, 1.0f};
/* Tan color { R:210, G:180, B:140, A:255 } */
sg_color sg_tan = sg_color{0.823529412f, 0.705882353f, 0.549019608f, 1.0f};
/* Teal color { R:0, G:128, B:128, A:255 } */
sg_color sg_teal = sg_color{0.0f, 0.501960784f, 0.501960784f, 1.0f};
/* Thistle color { R:216, G:191, B:216, A:255 } */
sg_color sg_thistle = sg_color{0.847058824f, 0.749019608f, 0.847058824f, 1.0f};
/* Tomato color { R:255, G:99, B:71, A:255 } */
sg_color sg_tomato = sg_color{1.0f, 0.388235294f, 0.278431373f, 1.0f};
/* Transparent color { R:0, G:0, B:0, A:0 } */
sg_color sg_transparent = sg_color{0.0f, 0.0f, 0.0f, 0.0f};
/* Turquoise color { R:64, G:224, B:208, A:255 } */
sg_color sg_turquoise = sg_color{0.250980392f, 0.878431373f, 0.815686275f, 1.0f};
/* Violet color { R:238, G:130, B:238, A:255 } */
sg_color sg_violet = sg_color{0.933333333f, 0.509803922f, 0.933333333f, 1.0f};
/* Wheat color { R:245, G:222, B:179, A:255 } */
sg_color sg_wheat = sg_color{0.960784314f, 0.870588235f, 0.701960784f, 1.0f};
/* White color { R:255, G:255, B:255, A:255 } */
sg_color sg_white = sg_color{1.0f, 1.0f, 1.0f, 1.0f};
/* White Smoke color { R:245, G:245, B:245, A:255 } */
sg_color sg_white_smoke = sg_color{0.960784314f, 0.960784314f, 0.960784314f, 1.0f};
/* Yellow color { R:255, G:255, B:0, A:255 } */
sg_color sg_yellow = sg_color{1.0f, 1.0f, 0.0f, 1.0f};
/* Yellow Green color { R:154, G:205, B:50, A:255 } */
sg_color sg_yellow_green = sg_color{0.603921569f, 0.803921569f, 0.196078431f, 1.0f};
}
private {
state_t state = state_t{
    .pass_action = sg_pass_action{
        .colors[0] = {
            .load_action = SG_LOADACTION_CLEAR,
            .clear_value = {0.690196078f, 0.188235294f, 0.376470588f, 1.0f},
        },
    },
};
}

private {
void init() {
    sg_setup(&sg_desc{.environment = sglue_environment(), .logger = sg_logger{.func = slog_func}});
    __dbgui_setup();
    sdtx_setup(&sdtx_desc_t{.fonts[0] = sdtx_font_c64(), .logger = sdtx_logger_t{.func = slog_func}});
    if sg_query_features().draw_base_vertex != 0 {
        state.supported_modes |= cast(u8, BASE_VERTEX);
    }
    if sg_query_features().draw_base_instance != 0 {
        state.supported_modes |= cast(u8, BASE_INSTANCE | BASE_VERTEX_INSTANCE);
    }
    state.current_mode = BASE_VERTEX_INSTANCE & state.supported_modes;
    vertex_t[7] vertices = {
        vertex_t{.x = 0.0f, .y = 0.55f, .r = 1.0f, .g = 1.0f, .b = 0.0f},
        vertex_t{.x = 0.25f, .y = 0.05f, .r = 0.0f, .g = 1.0f, .b = 1.0f},
        vertex_t{.x = -0.25f, .y = 0.05f, .r = 1.0f, .g = 0.0f, .b = 1.0f},
        vertex_t{.x = -0.25f, .y = -0.05f, .r = 0.5f, .g = 0.0f, .b = 1.0f},
        vertex_t{.x = 0.25f, .y = -0.05f, .r = 0.5f, .g = 1.0f, .b = 0.0f},
        vertex_t{.x = 0.25f, .y = -0.55f, .r = 0.0f, .g = 1.0f, .b = 0.5f},
        vertex_t{.x = -0.25f, .y = -0.55f, .r = 1.0f, .g = 0.0f, .b = 0.5f},
    };
    u16[9] indices = {0, 1, 2, 0, 1, 2, 0, 2, 3};
    state.vtx_buf = sg_make_buffer(&sg_buffer_desc{
        .usage = sg_buffer_usage{.vertex_buffer = true},
        .data = sg_range{&vertices, sizeof(vertices)},
        .label = "vertex-buffer",
    });
    state.idx_buf = sg_make_buffer(&sg_buffer_desc{
        .usage = sg_buffer_usage{.index_buffer = true},
        .data = sg_range{&indices, sizeof(indices)},
        .label = "index-buffer",
    });
    f32 off_y = -0.2f;
    f32 dx = 0.3f;
    f32 dy = 0.4f;
    f32 s = 0.4f;
    instance_t[6] instances = {
        instance_t{.x = -dx, .y = -dy + off_y, .scale = s},
        instance_t{.x = dx, .y = 0.0f + off_y, .scale = s},
        instance_t{.x = -dx, .y = dy + off_y, .scale = s},
        instance_t{.x = dx, .y = -dy + off_y, .scale = s},
        instance_t{.x = -dx, .y = 0.0f + off_y, .scale = s},
        instance_t{.x = dx, .y = dy + off_y, .scale = s},
    };
    state.inst_buf = sg_make_buffer(&sg_buffer_desc{
        .usage = sg_buffer_usage{.vertex_buffer = true},
        .data = sg_range{&instances, sizeof(instances)},
        .label = "instance-buffer",
    });
    state.pip = sg_make_pipeline(&sg_pipeline_desc{
        .shader = sokol_make_shader(&drawex_sapp_vs_shader, &drawex_sapp_fs_shader),
        .index_type = SG_INDEXTYPE_UINT16,
        .layout = sg_vertex_layout_state{
            .buffers[1] = {.step_func = SG_VERTEXSTEP_PER_INSTANCE},
            .attrs = {
                sg_vertex_attr_state{.format = SG_VERTEXFORMAT_FLOAT2, .buffer_index = 0},
                sg_vertex_attr_state{.format = SG_VERTEXFORMAT_FLOAT3, .buffer_index = 0},
                sg_vertex_attr_state{.format = SG_VERTEXFORMAT_FLOAT3, .buffer_index = 1},
                sg_vertex_attr_state{},
                sg_vertex_attr_state{},
                sg_vertex_attr_state{},
                sg_vertex_attr_state{},
                sg_vertex_attr_state{},
                sg_vertex_attr_state{},
                sg_vertex_attr_state{},
                sg_vertex_attr_state{},
                sg_vertex_attr_state{},
                sg_vertex_attr_state{},
                sg_vertex_attr_state{},
                sg_vertex_attr_state{},
                sg_vertex_attr_state{},
            },
        },
        .label = "render-pipeline",
    });
}

void frame() {
    draw_panel();
    sg_begin_pass(&sg_pass{.action = state.pass_action, .swapchain = sglue_swapchain()});
    sg_apply_pipeline(state.pip);
    sg_apply_bindings(&sg_bindings{
        .vertex_buffers = {
            state.vtx_buf,
            state.inst_buf,
            sg_buffer{},
            sg_buffer{},
            sg_buffer{},
            sg_buffer{},
            sg_buffer{},
            sg_buffer{},
        },
        .index_buffer = state.idx_buf,
    });
    i32 tri_base_index = 0;
    i32 tri_num_indices = 3;
    i32 quad_base_index = 3;
    i32 quad_num_indices = 6;
    i32 num_instances = 3;
    i32 tri_base_vertex = 0;
    i32 quad_base_vertex = 3;
    i32 left_inst_base = 0;
    i32 right_inst_base = 3;
    switch state.current_mode {
        case BASE_VERTEX: {
            sg_draw_ex(tri_base_index, tri_num_indices, num_instances, tri_base_vertex, left_inst_base);
            sg_draw_ex(quad_base_index, quad_num_indices, num_instances, quad_base_vertex, left_inst_base);
        }
        case BASE_INSTANCE: {
            sg_draw_ex(tri_base_index, tri_num_indices, num_instances, tri_base_vertex, left_inst_base);
            sg_draw_ex(tri_base_index, tri_num_indices, num_instances, tri_base_vertex, right_inst_base);
        }
        case BASE_VERTEX_INSTANCE: {
            sg_draw_ex(tri_base_index, tri_num_indices, num_instances, tri_base_vertex, left_inst_base);
            sg_draw_ex(quad_base_index, quad_num_indices, num_instances, quad_base_vertex, left_inst_base);
            sg_draw_ex(tri_base_index, tri_num_indices, num_instances, tri_base_vertex, right_inst_base);
            sg_draw_ex(quad_base_index, quad_num_indices, num_instances, quad_base_vertex, right_inst_base);
        }
        default: {
        }
    }
    sdtx_draw();
    __dbgui_draw();
    sg_end_pass();
    sg_commit();
}

void input(sapp_event* ev) {
    if ev.type == SAPP_EVENTTYPE_KEY_DOWN {
        switch ev.key_code {
            case SAPP_KEYCODE_1: {
                state.current_mode = BASE_VERTEX;
            }
            case SAPP_KEYCODE_2: {
                state.current_mode = BASE_INSTANCE;
            }
            case SAPP_KEYCODE_3: {
                state.current_mode = BASE_VERTEX_INSTANCE;
            }
            default: {
            }
        }
    }
    state.current_mode &= state.supported_modes;
    __dbgui_event(ev);
}

void cleanup() {
    sdtx_shutdown();
    __dbgui_shutdown();
    sg_shutdown();
}

void draw_panel() {
    sdtx_canvas(cast(f32, sapp_width()) * 0.5f, cast(f32, sapp_height()) * 0.5f);
    sdtx_origin(1.0f, 2.0f);
    sdtx_home();
    if state.supported_modes != 0 {
        sdtx_printf("Press keys 1,2,3:\n\n");
    }
    if (state.supported_modes & BASE_VERTEX) != 0 {
        sdtx_printf("%c (1) draw with base vertex\n", state.current_mode == BASE_VERTEX ? 42 : 32);
    } else {
        sdtx_puts("!!! base vertex not supported\n");
    }
    if (state.supported_modes & BASE_INSTANCE) != 0 {
        sdtx_printf("%c (2) draw with base instance\n", state.current_mode == BASE_INSTANCE ? 42 : 32);
    } else {
        sdtx_puts("!!! base instance not supported\n");
    }
    if (state.supported_modes & BASE_VERTEX_INSTANCE) != 0 {
        sdtx_printf("%c (3) draw with base vertex + base instance\n", state.current_mode == BASE_VERTEX_INSTANCE ? 42 : 32);
    } else {
        sdtx_puts("!!! base vertex + base instance not supported\n");
    }
}
}

sapp_desc __sapp_sample_main() {
    return sapp_desc{
        .init_cb = init,
        .frame_cb = frame,
        .cleanup_cb = cleanup,
        .event_cb = input,
        .width = 800,
        .height = 600,
        .sample_count = 4,
        .depth_format = SAPP_PIXELFORMAT_NONE,
        .window_title = "drawex-sapp.mc",
        .icon = sapp_icon_desc{.sokol_default = true},
        .logger = sapp_logger{.func = slog_func},
    };
}
